version: '3'
services:

  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo/myapp
      - PORT=3001
      - SECRET=G9UW3BBI5QlVJjL54VOpXR1/aD/ahEQPjpSBBsK9IWc=
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
